### ISSUE TITLE
1016 会員情報変更ページのCSSをお願いします

### ISSUE THREAD

**Issue by erina-11** [erina-11/jiriki#34]
参考になるかなとfigma載せてますが、自由な発想で作ってもらえると助かります。

**Comment by erina-11** [comment]
![image](https://user-images.githubusercontent.com/74029789/132880737-10e0ea7a-6e82-4256-8fea-89c54451330a.png)

**Comment by yorunegy** [comment]
以前ログインページを綺麗にするときにつかったBootstrapで綺麗な枠を作りましょう。

さらに、bootstrapのgridをつかって綺麗に並べましょう。

bootstrapのチートシートをみながら。
https://hackerthemes.com/bootstrap-cheatsheet/
