### ISSUE TITLE
1106 トップページをレスポンシブ対応しましょう

### ISSUE THREAD

**Issue by yorunegy** [erina-11/jiriki#49]
画面の大きさに応じて勝手に並び替えが変わるように

![image](https://user-images.githubusercontent.com/50258175/138487937-799a631c-0402-41b5-b3ed-d094a6cb4f12.png)

![image](https://user-images.githubusercontent.com/50258175/138488021-694039eb-9351-4805-90df-0135e5ef3ace.png)

【ヒント】
flexboxというものを使います。　
※flexboxって何だろう　→　https://flexbox-cheat.site/

本当はCSSを色々と書かないといけませんが、bootstrapはそのへんも丸っとやってくれます。便利だね！
※bootstrapでflexboxを使う方法　→　https://getbootstrap.jp/docs/4.2/utilities/flex/

```
<div class="d-flex">
...
</div>
```

で囲むだけで、この囲まれたものはすべてflexboxが適用されます。
つまり自由に右寄せしたり真ん中寄せしたり、幅いっぱいに広げたり、画面の大きさによって並び替えをかえたりできます。どうしたいかを、d-flex以外のクラスを指定することで調整できます。

今回は画面の大きさによって並び替えてほしいので、flex-wrapというものをつかいます。
※逆に画面の大きさに関わらず並び替えを固定したいとか、色んな使い方はさっきのリンクの先に説明が書いてあります　→　https://getbootstrap.jp/docs/4.2/utilities/flex/

```
<div class="d-flex flex-wrap">
...
</div>
```

【ミッション】
さて、ではこれをつかって、index.phpのどこからどこを囲めばいいんでしょうか？
ここは頭をつかって自分で考えてみましょう！

**Comment by LinkGubei15** [comment]
@yorunegy 何度挑戦してもうまくいきません。

**Comment by yorunegy** [comment]
@LinkGubei15 こちらではうまくいくんだけどなぁ。。。
今日もう一度みてみましょう！
