### ISSUE TITLE
0219 おしゃべりページ（plan-talk.php）で投稿と表示ができるようにしよう

### ISSUE THREAD

**Issue by yorunegy** [erina-11/jiriki#55]
今はこう。投稿も表示もない。
![image](https://user-images.githubusercontent.com/50258175/140596684-4f2b3224-6aaf-43df-8f7c-bf35b6d80913.png)

例ですが、こんな感じで投稿内容を表示できるようにしましょう。
![image](https://user-images.githubusercontent.com/50258175/140596719-5827fd48-3ae0-43b0-b1c1-39537667e531.png)

１．イベントごとに表示されるおしゃべりが変わるよ
２．そのためにはこのページにくるときに、イベントのIDが必要だね
　→　plan_detail.phpを修正しよう
３．まず全部のおしゃべりをとってきて表示しよう
　→　index.phpでは「すべてのイベント」をとってきてる
　→　つまりこれをちょっと変えて、「すべてのおしゃべり」を取ってくればいい

【学習ポイント】
・データベースの作り方
・データベースへの書き込み（INSERT）の方法
・データベースからの読み込み（SELECT）の方法
・参考：このあたりを家で見ておこう
https://dotinstall.com/lessons/basic_php_db_v2
https://prog-8.com/lessons/php/study/4

**Comment by yorunegy** [comment]
１．XAMPP＞MySQL＞Admin＞jirikiから、新しいテーブルをつくる（名前はplan_chat）
２．plan_act.phpをコピーして、ちょっと変えてplan_chatに追加できるようにする

**Comment by LinkGubei15** [comment]
ok  ^^)
