### ISSUE TITLE
0903 トップページを綺麗にしてみよう

### ISSUE THREAD

**Issue by yorunegy** [erina-11/jiriki#76]
![image](https://user-images.githubusercontent.com/50258175/188190812-ac7f9ba5-0b65-445d-8df9-84a6d7a2ee27.png)

こんな感じにカードとボタンでデザインしてみましょう。
css/ueno.css
をいじくればうまくいくはずです。

**Comment by erina-11** [comment]
![image](https://user-images.githubusercontent.com/74029789/198685849-558865fa-4e67-4099-b99a-7007cd46c46d.png)

このリンクもすべて「アイコン付」のボタンにしましょう
